name: Deploy updates
on:
  push:
    branches:
      - main
jobs:
  deploy-prod:
    env:
      LABPASSPHRASE: ${{ secrets.LABPASSPHRASE }}
    timeout-minutes: 15
    runs-on: self-hosted
    steps:
      - name: Hi
        run: echo "Hello World!"
      - name: Checkout
        uses: actions/checkout@v4
      [...]
      - name: Test site1
        run: make validate-site-1
        working-directory: labs/L3LS_EVPN/
        if: steps.filter-site1.outputs.workflows == 'true'
      - name: Expose Site 1 test report in Github Action
        run: cat labs/L3LS_EVPN/sites/site_1/anta/reports/anta_report.md >> $GITHUB_STEP_SUMMARY
        if: steps.filter-site1.outputs.workflows == 'true'